import type { Scene } from '@cg/shared-schema';
import { anim, EASE, kf, track } from './anim.js';

/**
 * Breaking news — a bottom-third alert: a gradient panel slides up, a
 * yellow rule wipes across the top, a kicker plate pops in with its
 * label, the headline rises and fades, and a "LIVE" dot pulses. Showcases:
 * vertical gradient, scale-x wipe, overshoot pop, slide+fade, opacity loop.
 */
export const breakingNewsScene: Scene = {
  schemaVersion: 1,
  id: 'starter-breaking-news',
  name: 'Breaking News',
  templateType: 'breaking-news',
  resolution: { width: 1920, height: 1080 },
  frameRate: 50,
  safeAreas: { title: 10, action: 5 },
  frameRange: { in: 0, out: 90 },
  background: 'transparent',
  layers: [
    {
      id: 'L1',
      name: 'Banner',
      visible: true,
      locked: false,
      blendMode: 'normal',
      children: [
        {
          id: 'panel',
          name: 'panel-bg',
          type: 'shape',
          transform: {
            position: { x: 0, y: 718 },
            size: { w: 1920, h: 302 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 0.98,
          visible: true,
          locked: false,
          zIndex: 0,
          shape: 'rect',
          fill: {
            kind: 'linear',
            angle: 90,
            stops: [
              { at: 0, color: '#991B1B' },
              { at: 1, color: '#450A0A' },
            ],
          },
          shadow: { offsetX: 0, offsetY: -8, blur: 30, color: '#00000066' },
          animation: anim({
            'position.y': track(kf(0, 1020, EASE.outExpo), kf(18, 718, EASE.outExpo)),
          }),
        },
        {
          id: 'rule',
          name: 'top-rule',
          type: 'shape',
          transform: {
            position: { x: 0, y: 712 },
            size: { w: 1920, h: 6 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0.5 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 1,
          shape: 'rect',
          fill: { kind: 'solid', color: '#FACC15' },
          animation: anim({
            'scale.x': track(kf(6, 0, EASE.outExpo), kf(26, 1, EASE.outExpo)),
          }),
        },
        {
          id: 'kicker-plate',
          name: 'kicker-plate',
          type: 'shape',
          transform: {
            position: { x: 64, y: 744 },
            size: { w: 300, h: 58 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0.5 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 2,
          shape: 'rounded-rect',
          cornerRadius: 6,
          fill: { kind: 'solid', color: '#FACC15' },
          animation: anim({
            'scale.x': track(kf(8, 0, EASE.outBack), kf(26, 1, EASE.outBack)),
          }),
        },
        {
          id: 'kicker',
          name: 'kicker-text',
          type: 'text',
          transform: {
            position: { x: 84, y: 752 },
            size: { w: 280, h: 44 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 3,
          text: '{{kicker}}',
          font: {
            family: 'Inter',
            weight: 800,
            style: 'normal',
            size: 30,
            lineHeight: 1.1,
            letterSpacing: 0.1,
          },
          color: '#0F172A',
          align: 'start',
          direction: 'auto',
          fitMode: 'autosize',
          overflow: 'clip',
          animation: anim({ opacity: track(kf(16, 0), kf(28, 1)) }),
        },
        {
          id: 'headline',
          name: 'headline-text',
          type: 'text',
          transform: {
            position: { x: 64, y: 826 },
            size: { w: 1660, h: 120 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 3,
          text: '{{headline}}',
          font: {
            family: 'Inter',
            weight: 800,
            style: 'normal',
            size: 62,
            lineHeight: 1.15,
            letterSpacing: -0.01,
          },
          color: '#FFFFFF',
          align: 'start',
          direction: 'auto',
          fitMode: 'autosize',
          overflow: 'ellipsis',
          maxLines: 2,
          wrap: true,
          animation: anim({
            opacity: track(kf(18, 0), kf(34, 1)),
            'position.y': track(kf(18, 850, EASE.outExpo), kf(36, 826, EASE.outExpo)),
          }),
        },
        {
          id: 'timestamp',
          name: 'timestamp-text',
          type: 'text',
          transform: {
            position: { x: 64, y: 962 },
            size: { w: 900, h: 30 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 0.8,
          visible: true,
          locked: false,
          zIndex: 3,
          text: '{{strap}}',
          font: {
            family: 'Inter',
            weight: 500,
            style: 'normal',
            size: 24,
            lineHeight: 1.2,
            letterSpacing: 0.03,
          },
          color: '#FCA5A5',
          align: 'start',
          direction: 'auto',
          fitMode: 'fixed',
          overflow: 'ellipsis',
          animation: anim({ opacity: track(kf(26, 0), kf(40, 0.8)) }),
        },
        {
          id: 'livedot',
          name: 'live-dot',
          type: 'shape',
          transform: {
            position: { x: 1788, y: 770 },
            size: { w: 18, h: 18 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0.5, y: 0.5 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 3,
          shape: 'ellipse',
          fill: { kind: 'solid', color: '#FACC15' },
          animation: anim({
            opacity: track(
              kf(20, 1, EASE.inOut),
              kf(45, 0.2, EASE.inOut),
              kf(70, 1, EASE.inOut),
              kf(90, 0.2, EASE.inOut),
            ),
          }),
        },
        {
          id: 'livetext',
          name: 'live-text',
          type: 'text',
          transform: {
            position: { x: 1812, y: 762 },
            size: { w: 96, h: 34 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 0.9,
          visible: true,
          locked: false,
          zIndex: 3,
          text: 'LIVE',
          font: {
            family: 'Inter',
            weight: 800,
            style: 'normal',
            size: 26,
            lineHeight: 1.1,
            letterSpacing: 0.1,
          },
          color: '#FACC15',
          align: 'start',
          direction: 'ltr',
          fitMode: 'fixed',
          overflow: 'clip',
          animation: anim({ opacity: track(kf(22, 0), kf(34, 0.9)) }),
        },
      ],
    },
  ],
  fields: [
    { id: 'kicker', label: 'Kicker label', required: true, type: 'text', default: 'BREAKING' },
    {
      id: 'headline',
      label: 'Headline',
      required: true,
      type: 'text',
      default: 'Severe storm system makes landfall along the eastern seaboard',
    },
    {
      id: 'strap',
      label: 'Strapline',
      required: false,
      type: 'text',
      default: 'Live · Emergency services on scene',
    },
  ],
  bindings: [
    { fieldId: 'kicker', target: { kind: 'text', elementId: 'kicker', placeholder: '{{kicker}}' } },
    { fieldId: 'headline', target: { kind: 'text', elementId: 'headline', placeholder: '{{headline}}' } },
    { fieldId: 'strap', target: { kind: 'text', elementId: 'timestamp', placeholder: '{{strap}}' } },
  ],
  fonts: [{ family: 'Inter', weights: [500, 800], styles: ['normal'], source: 'system' }],
  metadata: {
    createdAt: '2026-06-04T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
    description: 'Bottom-third breaking alert with accent wipe and pulsing LIVE.',
    tags: ['starter', 'breaking-news', 'animated'],
  },
};
