import type { Scene } from '@cg/shared-schema';

/**
 * Breaking news starter — a large alert banner with a kicker label and
 * a one-line headline. Sized for full-width 1080p delivery.
 */
export const breakingNewsScene: Scene = {
  schemaVersion: 1,
  id: 'starter-breaking-news',
  name: 'Breaking News',
  templateType: 'breaking-news',
  resolution: { width: 1920, height: 1080 },
  frameRate: 50,
  safeAreas: { title: 10, action: 5 },
  background: 'transparent',
  layers: [
    {
      id: 'L1',
      name: 'Banner',
      visible: true,
      locked: false,
      blendMode: 'normal',
      children: [
        {
          id: 'panel',
          name: 'panel-bg',
          type: 'shape',
          transform: {
            position: { x: 0, y: 720 },
            size: { w: 1920, h: 240 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 0.97,
          visible: true,
          locked: false,
          zIndex: 0,
          shape: 'rect',
          fill: { kind: 'solid', color: '#7F1D1D' },
        },
        {
          id: 'kicker-plate',
          name: 'kicker-plate',
          type: 'shape',
          transform: {
            position: { x: 60, y: 740 },
            size: { w: 320, h: 60 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 1,
          shape: 'rect',
          fill: { kind: 'solid', color: '#FACC15' },
        },
        {
          id: 'kicker',
          name: 'kicker-text',
          type: 'text',
          transform: {
            position: { x: 60, y: 750 },
            size: { w: 320, h: 50 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 2,
          text: '{{kicker}}',
          font: {
            family: 'Inter',
            weight: 800,
            style: 'normal',
            size: 32,
            lineHeight: 1.1,
            letterSpacing: 0.05,
          },
          color: '#0F172A',
          align: 'center',
          direction: 'auto',
          fitMode: 'autosize',
          overflow: 'clip',
        },
        {
          id: 'headline',
          name: 'headline-text',
          type: 'text',
          transform: {
            position: { x: 60, y: 830 },
            size: { w: 1800, h: 120 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 2,
          text: '{{headline}}',
          font: {
            family: 'Inter',
            weight: 800,
            style: 'normal',
            size: 64,
            lineHeight: 1.2,
            letterSpacing: 0,
          },
          color: '#FFFFFF',
          align: 'start',
          direction: 'auto',
          fitMode: 'autosize',
          overflow: 'ellipsis',
        },
      ],
    },
  ],
  fields: [
    {
      id: 'kicker',
      label: 'Kicker label',
      required: true,
      type: 'text',
      default: 'BREAKING',
    },
    {
      id: 'headline',
      label: 'Headline',
      required: true,
      type: 'text',
      default: 'Major event reported — details below',
    },
  ],
  bindings: [
    {
      fieldId: 'kicker',
      target: { kind: 'text', elementId: 'kicker', placeholder: '{{kicker}}' },
    },
    {
      fieldId: 'headline',
      target: { kind: 'text', elementId: 'headline', placeholder: '{{headline}}' },
    },
  ],
  fonts: [],
  metadata: {
    createdAt: '2026-05-24T00:00:00.000Z',
    updatedAt: '2026-05-24T00:00:00.000Z',
    description: 'M8.3 starter — yellow-kicker breaking-news banner.',
    tags: ['starter', 'breaking-news'],
  },
};
