import type { Scene } from '@cg/shared-schema';
import { anim, EASE, kf, kfLinear, track } from './anim.js';

/**
 * Fullscreen title — the showpiece. A radial-gradient stage, two slowly
 * drifting decorative rings, a kicker, a hero title that focuses in
 * (blur → 0) while it scales up and its letter-spacing tightens, an accent
 * rule that wipes open, and a subtitle that rises. Showcases: radial +
 * linear gradients, animated `filter.blur`, animated `font.letterSpacing`,
 * scale-about-centre, slow looping rotation, scale-x wipe.
 */
export const fullscreenScene: Scene = {
  schemaVersion: 1,
  id: 'starter-fullscreen',
  name: 'Fullscreen Title',
  templateType: 'fullscreen',
  resolution: { width: 1920, height: 1080 },
  frameRate: 50,
  safeAreas: { title: 10, action: 5 },
  frameRange: { in: 0, out: 110 },
  background: 'transparent',
  layers: [
    {
      id: 'L1',
      name: 'Title Card',
      visible: true,
      locked: false,
      blendMode: 'normal',
      children: [
        {
          id: 'stage',
          name: 'stage-bg',
          type: 'shape',
          transform: {
            position: { x: 0, y: 0 },
            size: { w: 1920, h: 1080 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 0,
          shape: 'rect',
          fill: {
            kind: 'radial',
            center: { x: 0.5, y: 0.42 },
            radius: 1300,
            stops: [
              { at: 0, color: '#23365F' },
              { at: 0.55, color: '#111d38' },
              { at: 1, color: '#05080F' },
            ],
          },
          animation: anim({ opacity: track(kf(0, 0, EASE.outCubic), kf(12, 1, EASE.outCubic)) }),
        },
        {
          id: 'ring1',
          name: 'deco-ring-1',
          type: 'shape',
          transform: {
            position: { x: 1180, y: -240 },
            size: { w: 1000, h: 1000 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0.5, y: 0.5 },
          },
          opacity: 0.12,
          visible: true,
          locked: false,
          zIndex: 1,
          shape: 'ellipse',
          stroke: { width: 2, color: '#7DD3FC', dash: [2, 14] },
          animation: anim({
            rotation: track(kfLinear(0, 0), kfLinear(110, 60)),
            opacity: track(kf(0, 0), kf(30, 0.14)),
          }),
        },
        {
          id: 'ring2',
          name: 'deco-ring-2',
          type: 'shape',
          transform: {
            position: { x: -160, y: 920 },
            size: { w: 720, h: 720 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0.5, y: 0.5 },
          },
          opacity: 0.1,
          visible: true,
          locked: false,
          zIndex: 1,
          shape: 'ellipse',
          stroke: { width: 2, color: '#38BDF8' },
          animation: anim({
            rotation: track(kfLinear(0, 40), kfLinear(110, -20)),
            opacity: track(kf(0, 0), kf(30, 0.12)),
          }),
        },
        {
          id: 'kicker',
          name: 'kicker',
          type: 'text',
          transform: {
            position: { x: 360, y: 392 },
            size: { w: 1200, h: 36 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0.5, y: 0.5 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 2,
          text: '{{kicker}}',
          font: {
            family: 'Inter',
            weight: 700,
            style: 'normal',
            size: 24,
            lineHeight: 1.2,
            letterSpacing: 0.4,
          },
          color: '#7DD3FC',
          align: 'center',
          direction: 'auto',
          fitMode: 'fixed',
          overflow: 'clip',
          animation: anim({
            opacity: track(kf(14, 0), kf(28, 1)),
            'position.y': track(kf(14, 410, EASE.outExpo), kf(30, 392, EASE.outExpo)),
          }),
        },
        {
          id: 'title',
          name: 'hero-title',
          type: 'text',
          transform: {
            position: { x: 160, y: 446 },
            size: { w: 1600, h: 150 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0.5, y: 0.5 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 3,
          text: '{{title}}',
          font: {
            family: 'Inter',
            weight: 800,
            style: 'normal',
            size: 116,
            lineHeight: 1.05,
            letterSpacing: 0.04,
          },
          color: '#FFFFFF',
          align: 'center',
          direction: 'auto',
          fitMode: 'autosize',
          overflow: 'clip',
          textShadow: { offsetX: 0, offsetY: 14, blur: 40, color: '#00000080' },
          filter: { blur: 0 },
          animation: anim({
            opacity: track(kf(6, 0, EASE.outCubic), kf(26, 1, EASE.outCubic)),
            'scale.x': track(kf(6, 0.9, EASE.outExpo), kf(34, 1, EASE.outExpo)),
            'scale.y': track(kf(6, 0.9, EASE.outExpo), kf(34, 1, EASE.outExpo)),
            'filter.blur': track(kf(6, 18, EASE.outCubic), kf(30, 0, EASE.outCubic)),
            'font.letterSpacing': track(kf(6, 0.34, EASE.outExpo), kf(34, 0.04, EASE.outExpo)),
          }),
        },
        {
          id: 'rule',
          name: 'accent-rule',
          type: 'shape',
          transform: {
            position: { x: 810, y: 624 },
            size: { w: 300, h: 5 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0.5, y: 0.5 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 3,
          shape: 'rect',
          fill: {
            kind: 'linear',
            angle: 0,
            stops: [
              { at: 0, color: '#38BDF8' },
              { at: 1, color: '#818CF8' },
            ],
          },
          animation: anim({
            'scale.x': track(kf(24, 0, EASE.outExpo), kf(44, 1, EASE.outExpo)),
          }),
        },
        {
          id: 'subtitle',
          name: 'subtitle',
          type: 'text',
          transform: {
            position: { x: 360, y: 648 },
            size: { w: 1200, h: 46 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0.5, y: 0.5 },
          },
          opacity: 0.85,
          visible: true,
          locked: false,
          zIndex: 3,
          text: '{{subtitle}}',
          font: {
            family: 'Inter',
            weight: 500,
            style: 'normal',
            size: 30,
            lineHeight: 1.3,
            letterSpacing: 0.05,
          },
          color: '#AFC0DE',
          align: 'center',
          direction: 'auto',
          fitMode: 'fixed',
          overflow: 'ellipsis',
          animation: anim({
            opacity: track(kf(34, 0), kf(50, 0.85)),
            'position.y': track(kf(34, 668, EASE.outExpo), kf(52, 648, EASE.outExpo)),
          }),
        },
      ],
    },
  ],
  fields: [
    { id: 'kicker', label: 'Kicker', required: false, type: 'text', default: 'SPECIAL REPORT' },
    { id: 'title', label: 'Title', required: true, type: 'text', default: 'The Road Ahead' },
    {
      id: 'subtitle',
      label: 'Subtitle',
      required: false,
      type: 'text',
      default: 'A documentary in three parts · Premieres Friday',
    },
  ],
  bindings: [
    { fieldId: 'kicker', target: { kind: 'text', elementId: 'kicker', placeholder: '{{kicker}}' } },
    { fieldId: 'title', target: { kind: 'text', elementId: 'title', placeholder: '{{title}}' } },
    {
      fieldId: 'subtitle',
      target: { kind: 'text', elementId: 'subtitle', placeholder: '{{subtitle}}' },
    },
  ],
  fonts: [{ family: 'Inter', weights: [500, 700, 800], styles: ['normal'], source: 'system' }],
  metadata: {
    createdAt: '2026-06-04T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
    description: 'Cinematic full-frame title: radial stage, blur focus-in, letter-spacing reveal.',
    tags: ['starter', 'fullscreen', 'animated'],
  },
};
