import type { Scene } from '@cg/shared-schema';
import { anim, EASE, kf, track } from './anim.js';

/**
 * "Aurora" lower third (English) — a glassy gradient plate with a colour
 * accent bar, animated name + role. Showcases: linear-gradient fill, drop
 * shadow, a scale-wipe reveal, slide-and-fade text, and bound colour +
 * text fields.
 *
 * Timeline (50 fps): plate wipes open (0–16), accent grows (6–22),
 * name slides up & fades (12–28), role follows (18–34); holds to 90.
 */
export const lowerThirdScene: Scene = {
  schemaVersion: 1,
  id: 'starter-lower-third',
  name: 'Aurora Lower Third',
  templateType: 'lower-third',
  resolution: { width: 1920, height: 1080 },
  frameRate: 50,
  safeAreas: { title: 10, action: 5 },
  frameRange: { in: 0, out: 90 },
  background: 'transparent',
  layers: [
    {
      id: 'L1',
      name: 'Lower Third',
      visible: true,
      locked: false,
      blendMode: 'normal',
      children: [
        {
          id: 'plate',
          name: 'glass-plate',
          type: 'shape',
          transform: {
            position: { x: 120, y: 815 },
            size: { w: 920, h: 156 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0.5 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 0,
          shape: 'rounded-rect',
          cornerRadius: 16,
          fill: {
            kind: 'linear',
            angle: 105,
            stops: [
              { at: 0, color: '#0B1224' },
              { at: 1, color: '#1E2A47' },
            ],
          },
          shadow: { offsetX: 0, offsetY: 20, blur: 48, color: '#00000099' },
          animation: anim({
            'scale.x': track(kf(0, 0, EASE.outExpo), kf(16, 1, EASE.outExpo)),
            opacity: track(kf(0, 0, EASE.outCubic), kf(8, 1, EASE.outCubic)),
          }),
        },
        {
          id: 'accent',
          name: 'accent-bar',
          type: 'shape',
          transform: {
            position: { x: 120, y: 815 },
            size: { w: 8, h: 156 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 1 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 1,
          shape: 'rect',
          fill: { kind: 'solid', color: '#38BDF8' },
          animation: anim({
            'scale.y': track(kf(6, 0, EASE.outBack), kf(24, 1, EASE.outBack)),
          }),
        },
        {
          id: 'kicker',
          name: 'kicker-label',
          type: 'text',
          transform: {
            position: { x: 156, y: 838 },
            size: { w: 820, h: 28 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 2,
          text: 'LIVE REPORT',
          font: {
            family: 'Inter',
            weight: 700,
            style: 'normal',
            size: 18,
            lineHeight: 1.2,
            letterSpacing: 0.22,
          },
          color: '#7DD3FC',
          align: 'start',
          direction: 'ltr',
          fitMode: 'fixed',
          overflow: 'clip',
          animation: anim({
            opacity: track(kf(10, 0), kf(22, 1)),
            'position.x': track(kf(10, 176, EASE.outExpo), kf(24, 156, EASE.outExpo)),
          }),
        },
        {
          id: 'name',
          name: 'name-text',
          type: 'text',
          transform: {
            position: { x: 156, y: 866 },
            size: { w: 840, h: 60 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 2,
          text: '{{name}}',
          font: {
            family: 'Inter',
            weight: 800,
            style: 'normal',
            size: 50,
            lineHeight: 1.1,
            letterSpacing: -0.01,
          },
          color: '#FFFFFF',
          align: 'start',
          direction: 'auto',
          fitMode: 'autosize',
          overflow: 'ellipsis',
          animation: anim({
            opacity: track(kf(14, 0), kf(28, 1)),
            'position.y': track(kf(14, 888, EASE.outExpo), kf(30, 866, EASE.outExpo)),
          }),
        },
        {
          id: 'role',
          name: 'role-text',
          type: 'text',
          transform: {
            position: { x: 156, y: 924 },
            size: { w: 840, h: 34 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 0.92,
          visible: true,
          locked: false,
          zIndex: 2,
          text: '{{title}}',
          font: {
            family: 'Inter',
            weight: 500,
            style: 'normal',
            size: 26,
            lineHeight: 1.2,
            letterSpacing: 0.01,
          },
          color: '#9FB3D1',
          align: 'start',
          direction: 'auto',
          fitMode: 'autosize',
          overflow: 'ellipsis',
          animation: anim({
            opacity: track(kf(20, 0), kf(34, 0.92)),
            'position.y': track(kf(20, 942, EASE.outExpo), kf(36, 924, EASE.outExpo)),
          }),
        },
      ],
    },
  ],
  fields: [
    { id: 'name', label: 'Name', required: true, type: 'text', default: 'Alex Morgan' },
    {
      id: 'title',
      label: 'Title / role',
      required: false,
      type: 'text',
      default: 'Senior Correspondent · London',
    },
    { id: 'accent', label: 'Accent colour', required: false, type: 'color', default: '#38BDF8' },
  ],
  bindings: [
    { fieldId: 'name', target: { kind: 'text', elementId: 'name', placeholder: '{{name}}' } },
    { fieldId: 'title', target: { kind: 'text', elementId: 'role', placeholder: '{{title}}' } },
    { fieldId: 'accent', target: { kind: 'color', elementId: 'accent', property: 'fill' } },
  ],
  fonts: [{ family: 'Inter', weights: [500, 700, 800], styles: ['normal'], source: 'system' }],
  metadata: {
    createdAt: '2026-06-04T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
    description: 'Glassy gradient lower third with accent wipe and slide-in text.',
    tags: ['starter', 'lower-third', 'animated'],
  },
};
