import type { Scene } from '@cg/shared-schema';
import { anim, EASE, kf, track } from './anim.js';

/**
 * Quote card — a full-frame editorial citation: gradient stage, an
 * oversized decorative quotation mark, the quote (multiline, italic) that
 * rises and fades in, then the author with an accent underline that wipes
 * open. Showcases: linear gradient, multiline wrapped text, italic style,
 * a multiline dynamic field, scale+fade, underline wipe.
 */
export const quoteCardScene: Scene = {
  schemaVersion: 1,
  id: 'starter-quote-card',
  name: 'Quote Card',
  templateType: 'custom',
  resolution: { width: 1920, height: 1080 },
  frameRate: 50,
  safeAreas: { title: 10, action: 5 },
  frameRange: { in: 0, out: 100 },
  background: 'transparent',
  layers: [
    {
      id: 'L1',
      name: 'Quote',
      visible: true,
      locked: false,
      blendMode: 'normal',
      children: [
        {
          id: 'stage',
          name: 'stage-bg',
          type: 'shape',
          transform: {
            position: { x: 0, y: 0 },
            size: { w: 1920, h: 1080 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 0,
          shape: 'rect',
          fill: {
            kind: 'linear',
            angle: 135,
            stops: [
              { at: 0, color: '#0E1726' },
              { at: 1, color: '#1C2A45' },
            ],
          },
          animation: anim({ opacity: track(kf(0, 0, EASE.outCubic), kf(10, 1, EASE.outCubic)) }),
        },
        {
          id: 'mark',
          name: 'quote-mark',
          type: 'text',
          transform: {
            position: { x: 220, y: 180 },
            size: { w: 400, h: 320 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 1,
          text: '“',
          font: {
            family: 'Georgia',
            weight: 700,
            style: 'normal',
            size: 360,
            lineHeight: 1,
            letterSpacing: 0,
          },
          color: '#38BDF8',
          align: 'start',
          direction: 'ltr',
          fitMode: 'fixed',
          overflow: 'clip',
          animation: anim({
            opacity: track(kf(4, 0, EASE.outCubic), kf(22, 0.22, EASE.outCubic)),
            'scale.x': track(kf(4, 0.7, EASE.outBack), kf(26, 1, EASE.outBack)),
            'scale.y': track(kf(4, 0.7, EASE.outBack), kf(26, 1, EASE.outBack)),
          }),
        },
        {
          id: 'quote',
          name: 'quote-text',
          type: 'text',
          transform: {
            position: { x: 300, y: 360 },
            size: { w: 1320, h: 340 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 2,
          text: '{{quote}}',
          font: {
            family: 'Georgia',
            weight: 500,
            style: 'italic',
            size: 58,
            lineHeight: 1.35,
            letterSpacing: 0,
          },
          color: '#F1F5F9',
          align: 'start',
          direction: 'auto',
          fitMode: 'autosize',
          overflow: 'ellipsis',
          maxLines: 4,
          wrap: true,
          animation: anim({
            opacity: track(kf(16, 0), kf(36, 1)),
            'position.y': track(kf(16, 386, EASE.outExpo), kf(38, 360, EASE.outExpo)),
          }),
        },
        {
          id: 'underline',
          name: 'author-rule',
          type: 'shape',
          transform: {
            position: { x: 300, y: 742 },
            size: { w: 90, h: 5 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0.5 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 2,
          shape: 'rect',
          fill: { kind: 'solid', color: '#38BDF8' },
          animation: anim({
            'scale.x': track(kf(38, 0, EASE.outExpo), kf(56, 1, EASE.outExpo)),
          }),
        },
        {
          id: 'author',
          name: 'author-text',
          type: 'text',
          transform: {
            position: { x: 300, y: 762 },
            size: { w: 1320, h: 50 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 2,
          text: '{{author}}',
          font: {
            family: 'Inter',
            weight: 700,
            style: 'normal',
            size: 30,
            lineHeight: 1.2,
            letterSpacing: 0.05,
          },
          color: '#7DD3FC',
          align: 'start',
          direction: 'auto',
          fitMode: 'autosize',
          overflow: 'ellipsis',
          animation: anim({
            opacity: track(kf(40, 0), kf(56, 1)),
            'position.x': track(kf(40, 320, EASE.outExpo), kf(58, 300, EASE.outExpo)),
          }),
        },
      ],
    },
  ],
  fields: [
    {
      id: 'quote',
      label: 'Quote',
      required: true,
      type: 'multiline',
      default: 'Design is not just what it looks like and feels like. Design is how it works.',
      maxLines: 4,
    },
    { id: 'author', label: 'Attribution', required: false, type: 'text', default: 'Steve Jobs' },
  ],
  bindings: [
    { fieldId: 'quote', target: { kind: 'text', elementId: 'quote', placeholder: '{{quote}}' } },
    { fieldId: 'author', target: { kind: 'text', elementId: 'author', placeholder: '{{author}}' } },
  ],
  fonts: [{ family: 'Inter', weights: [700], styles: ['normal'], source: 'system' }],
  metadata: {
    createdAt: '2026-06-04T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
    description: 'Editorial quote card with oversized mark and author underline wipe.',
    tags: ['starter', 'quote', 'custom', 'animated'],
  },
};
