import type { Scene } from '@cg/shared-schema';
import { anim, EASE, kf, track } from './anim.js';

/**
 * Scoreboard / score bug — a top-centre bar that drops in, team colour
 * chips that grow, team names, and a score that pops. Showcases: gradient
 * plate, bound team colours, slide-down, scale-y chip grow, score pop with
 * overshoot, and four bound text fields.
 */
export const scoreboardScene: Scene = {
  schemaVersion: 1,
  id: 'starter-scoreboard',
  name: 'Scoreboard',
  templateType: 'custom',
  resolution: { width: 1920, height: 1080 },
  frameRate: 50,
  safeAreas: { title: 10, action: 5 },
  frameRange: { in: 0, out: 80 },
  background: 'transparent',
  layers: [
    {
      id: 'L1',
      name: 'Scoreboard',
      visible: true,
      locked: false,
      blendMode: 'normal',
      children: [
        {
          id: 'plate',
          name: 'score-plate',
          type: 'shape',
          transform: {
            position: { x: 560, y: 48 },
            size: { w: 800, h: 100 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0.5, y: 0 },
          },
          opacity: 0.98,
          visible: true,
          locked: false,
          zIndex: 0,
          shape: 'rounded-rect',
          cornerRadius: 14,
          fill: {
            kind: 'linear',
            angle: 90,
            stops: [
              { at: 0, color: '#1E293B' },
              { at: 1, color: '#0B1120' },
            ],
          },
          shadow: { offsetX: 0, offsetY: 12, blur: 34, color: '#00000080' },
          animation: anim({
            'position.y': track(kf(0, -120, EASE.outExpo), kf(18, 48, EASE.outExpo)),
            opacity: track(kf(0, 0, EASE.outCubic), kf(10, 0.98, EASE.outCubic)),
          }),
        },
        {
          id: 'scorebox',
          name: 'score-box',
          type: 'shape',
          transform: {
            position: { x: 860, y: 48 },
            size: { w: 200, h: 100 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 1,
          shape: 'rect',
          fill: { kind: 'solid', color: '#020617' },
          animation: anim({
            opacity: track(kf(0, 0), kf(20, 1)),
            'position.y': track(kf(0, -120, EASE.outExpo), kf(18, 48, EASE.outExpo)),
          }),
        },
        {
          id: 'homechip',
          name: 'home-chip',
          type: 'shape',
          transform: {
            position: { x: 560, y: 48 },
            size: { w: 14, h: 100 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 2,
          shape: 'rect',
          fill: { kind: 'solid', color: '#2563EB' },
          animation: anim({
            'scale.y': track(kf(20, 0, EASE.outBack), kf(36, 1, EASE.outBack)),
            'position.y': track(kf(0, -120, EASE.outExpo), kf(18, 48, EASE.outExpo)),
          }),
        },
        {
          id: 'awaychip',
          name: 'away-chip',
          type: 'shape',
          transform: {
            position: { x: 1346, y: 48 },
            size: { w: 14, h: 100 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 2,
          shape: 'rect',
          fill: { kind: 'solid', color: '#DC2626' },
          animation: anim({
            'scale.y': track(kf(20, 0, EASE.outBack), kf(36, 1, EASE.outBack)),
            'position.y': track(kf(0, -120, EASE.outExpo), kf(18, 48, EASE.outExpo)),
          }),
        },
        {
          id: 'home',
          name: 'home-name',
          type: 'text',
          transform: {
            position: { x: 600, y: 74 },
            size: { w: 250, h: 50 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 3,
          text: '{{home}}',
          font: {
            family: 'Inter',
            weight: 800,
            style: 'normal',
            size: 38,
            lineHeight: 1.1,
            letterSpacing: 0.05,
          },
          color: '#FFFFFF',
          align: 'start',
          direction: 'auto',
          fitMode: 'autosize',
          overflow: 'ellipsis',
          animation: anim({
            opacity: track(kf(22, 0), kf(36, 1)),
            'position.x': track(kf(22, 580, EASE.outExpo), kf(38, 600, EASE.outExpo)),
          }),
        },
        {
          id: 'away',
          name: 'away-name',
          type: 'text',
          transform: {
            position: { x: 1070, y: 74 },
            size: { w: 250, h: 50 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0, y: 0 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 3,
          text: '{{away}}',
          font: {
            family: 'Inter',
            weight: 800,
            style: 'normal',
            size: 38,
            lineHeight: 1.1,
            letterSpacing: 0.05,
          },
          color: '#FFFFFF',
          align: 'end',
          direction: 'auto',
          fitMode: 'autosize',
          overflow: 'ellipsis',
          animation: anim({
            opacity: track(kf(22, 0), kf(36, 1)),
            'position.x': track(kf(22, 1090, EASE.outExpo), kf(38, 1070, EASE.outExpo)),
          }),
        },
        {
          id: 'homescore',
          name: 'home-score',
          type: 'text',
          transform: {
            position: { x: 872, y: 64 },
            size: { w: 76, h: 72 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0.5, y: 0.5 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 3,
          text: '{{homeScore}}',
          font: {
            family: 'Inter',
            weight: 800,
            style: 'normal',
            size: 56,
            lineHeight: 1,
            letterSpacing: 0,
          },
          color: '#FFFFFF',
          align: 'center',
          direction: 'ltr',
          fitMode: 'fixed',
          overflow: 'clip',
          animation: anim({
            opacity: track(kf(30, 0), kf(40, 1)),
            'scale.x': track(kf(30, 0.4, EASE.outBack), kf(46, 1, EASE.outBack)),
            'scale.y': track(kf(30, 0.4, EASE.outBack), kf(46, 1, EASE.outBack)),
          }),
        },
        {
          id: 'sep',
          name: 'score-sep',
          type: 'text',
          transform: {
            position: { x: 942, y: 64 },
            size: { w: 36, h: 72 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0.5, y: 0.5 },
          },
          opacity: 0.5,
          visible: true,
          locked: false,
          zIndex: 3,
          text: '–',
          font: {
            family: 'Inter',
            weight: 700,
            style: 'normal',
            size: 48,
            lineHeight: 1,
            letterSpacing: 0,
          },
          color: '#94A3B8',
          align: 'center',
          direction: 'ltr',
          fitMode: 'fixed',
          overflow: 'clip',
          animation: anim({ opacity: track(kf(34, 0), kf(44, 0.5)) }),
        },
        {
          id: 'awayscore',
          name: 'away-score',
          type: 'text',
          transform: {
            position: { x: 972, y: 64 },
            size: { w: 76, h: 72 },
            scale: { x: 1, y: 1 },
            rotation: 0,
            anchor: { x: 0.5, y: 0.5 },
          },
          opacity: 1,
          visible: true,
          locked: false,
          zIndex: 3,
          text: '{{awayScore}}',
          font: {
            family: 'Inter',
            weight: 800,
            style: 'normal',
            size: 56,
            lineHeight: 1,
            letterSpacing: 0,
          },
          color: '#FFFFFF',
          align: 'center',
          direction: 'ltr',
          fitMode: 'fixed',
          overflow: 'clip',
          animation: anim({
            opacity: track(kf(30, 0), kf(40, 1)),
            'scale.x': track(kf(30, 0.4, EASE.outBack), kf(46, 1, EASE.outBack)),
            'scale.y': track(kf(30, 0.4, EASE.outBack), kf(46, 1, EASE.outBack)),
          }),
        },
      ],
    },
  ],
  fields: [
    { id: 'home', label: 'Home team', required: true, type: 'text', default: 'LIONS' },
    { id: 'away', label: 'Away team', required: true, type: 'text', default: 'EAGLES' },
    { id: 'homeScore', label: 'Home score', required: true, type: 'text', default: '2' },
    { id: 'awayScore', label: 'Away score', required: true, type: 'text', default: '1' },
    { id: 'homeColor', label: 'Home colour', required: false, type: 'color', default: '#2563EB' },
    { id: 'awayColor', label: 'Away colour', required: false, type: 'color', default: '#DC2626' },
  ],
  bindings: [
    { fieldId: 'home', target: { kind: 'text', elementId: 'home', placeholder: '{{home}}' } },
    { fieldId: 'away', target: { kind: 'text', elementId: 'away', placeholder: '{{away}}' } },
    { fieldId: 'homeScore', target: { kind: 'text', elementId: 'homescore', placeholder: '{{homeScore}}' } },
    { fieldId: 'awayScore', target: { kind: 'text', elementId: 'awayscore', placeholder: '{{awayScore}}' } },
    { fieldId: 'homeColor', target: { kind: 'color', elementId: 'homechip', property: 'fill' } },
    { fieldId: 'awayColor', target: { kind: 'color', elementId: 'awaychip', property: 'fill' } },
  ],
  fonts: [{ family: 'Inter', weights: [700, 800], styles: ['normal'], source: 'system' }],
  metadata: {
    createdAt: '2026-06-04T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
    description: 'Top-centre score bug with team colours and a popping score.',
    tags: ['starter', 'scoreboard', 'custom', 'animated'],
  },
};
