import * as os from 'node:os';
import * as path from 'node:path';
import { dialog, type BrowserWindow, type IpcMain } from 'electron';
import { AssetService } from './services/AssetService.js';
import { ExportService } from './services/ExportService.js';
import { FontService } from './services/FontService.js';
import { ProjectService } from './services/ProjectService.js';
import { PreviewService } from './preview/PreviewService.js';
import { registerDesignerIpc } from './ipc/register.js';

/**
 * Designer composition root.
 *
 * Constructs the five main-tier services + wires IPC against the
 * provided BrowserWindow's WebContents. Returns a shutdown handle.
 *
 * The pre-bundled `@cg/template-runtime` payload (`cgJs`) is injected
 * here. In production it ships as a resource file under
 * `apps/designer/resources/template-runtime/cg.js`, generated by the
 * build step. Tests inject a stub.
 *
 * `cgpreview://` protocol registration is the caller's job (it needs
 * the electron module and runs once at app.whenReady). See
 * `apps/designer/src/main/index.ts` for the wiring.
 */
export interface DesignerBootContext {
  ipcMain: IpcMain;
  window: BrowserWindow;
  /** Pre-bundled cg.js content. */
  cgJs: string;
  /** Optional override for the project working directory (sandboxes assets). */
  workingRoot?: string;
  /** Optional override for the recent-projects JSON. */
  recentFilePath?: string;
}

export interface DesignerBootHandle {
  projects: ProjectService;
  assets: AssetService;
  fonts: FontService;
  exporter: ExportService;
  preview: PreviewService;
  shutdown(): void;
}

export function bootDesigner(ctx: DesignerBootContext): DesignerBootHandle {
  const workingRoot =
    ctx.workingRoot ?? path.join(os.tmpdir(), 'cg-designer', 'projects', 'current');
  const recentFilePath = ctx.recentFilePath ?? path.join(os.tmpdir(), 'cg-designer', 'recent.json');

  const projects = new ProjectService({ recentFilePath });
  const assets = new AssetService({ workingRoot });
  const fonts = new FontService();
  const exporter = new ExportService({ cgJs: ctx.cgJs, assets });
  const preview = new PreviewService({ cgJs: ctx.cgJs, assets });

  // Auto-bind: whenever the active project changes, reload the preview.
  projects.on('active-changed', (info) => {
    if (info.scene !== null) preview.loadScene(info.scene);
    else preview.clear();
  });

  const unwire = registerDesignerIpc({
    ipcMain: ctx.ipcMain,
    webContents: ctx.window.webContents,
    projects,
    assets,
    exporter,
    preview,
    showOpenDialog: async () => {
      const result = await dialog.showOpenDialog(ctx.window, {
        title: 'Open scene',
        properties: ['openFile'],
        filters: [{ name: 'Scene', extensions: ['json'] }],
      });
      return result.canceled || result.filePaths[0] === undefined ? null : result.filePaths[0];
    },
    showSaveDialog: async () => {
      const result = await dialog.showSaveDialog(ctx.window, {
        title: 'Save scene as',
        defaultPath: 'scene.scene.json',
        filters: [{ name: 'Scene', extensions: ['json'] }],
      });
      return result.canceled || result.filePath === undefined ? null : result.filePath;
    },
  });

  return {
    projects,
    assets,
    fonts,
    exporter,
    preview,
    shutdown(): void {
      unwire();
    },
  };
}
