import * as os from 'node:os';
import * as path from 'node:path';
import type { BrowserWindow, IpcMain } from 'electron';
import { AssetService } from './services/AssetService.js';
import { ExportService } from './services/ExportService.js';
import { FontService } from './services/FontService.js';
import { ProjectService } from './services/ProjectService.js';
import { registerDesignerIpc } from './ipc/register.js';

/**
 * Designer composition root.
 *
 * Constructs the four main-tier services + wires IPC against the
 * provided BrowserWindow's WebContents. Returns a shutdown handle.
 *
 * The pre-bundled `@cg/template-runtime` payload (`cgJs`) is injected
 * here. In production it ships as a resource file under
 * `apps/designer/resources/template-runtime/cg.js`, generated by the
 * build step. Tests inject a stub.
 */
export interface DesignerBootContext {
  ipcMain: IpcMain;
  window: BrowserWindow;
  /** Pre-bundled cg.js content. */
  cgJs: string;
  /** Optional override for the project working directory (sandboxes assets). */
  workingRoot?: string;
  /** Optional override for the recent-projects JSON. */
  recentFilePath?: string;
}

export interface DesignerBootHandle {
  projects: ProjectService;
  assets: AssetService;
  fonts: FontService;
  exporter: ExportService;
  shutdown(): void;
}

export function bootDesigner(ctx: DesignerBootContext): DesignerBootHandle {
  const workingRoot =
    ctx.workingRoot ?? path.join(os.tmpdir(), 'cg-designer', 'projects', 'current');
  const recentFilePath = ctx.recentFilePath ?? path.join(os.tmpdir(), 'cg-designer', 'recent.json');

  const projects = new ProjectService({ recentFilePath });
  const assets = new AssetService({ workingRoot });
  const fonts = new FontService();
  const exporter = new ExportService({ cgJs: ctx.cgJs, assets });

  const unwire = registerDesignerIpc({
    ipcMain: ctx.ipcMain,
    webContents: ctx.window.webContents,
    projects,
    assets,
    exporter,
  });

  return {
    projects,
    assets,
    fonts,
    exporter,
    shutdown(): void {
      unwire();
    },
  };
}
