import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { unpack } from '@cg/vcg-format';
import type { Scene } from '@cg/shared-schema';
import { ExporterSingleFile } from '../src/platform/ExporterSingleFile.js';
import type { AssetStore } from '../src/platform/AssetStore.js';

/**
 * B-034 — the exporter guard asserted against the REAL committed `.vcg` (not inline comps). The
 * fixture (generated by fixtures/b034/hidden-content-inert.gen.mjs) is unpacked here, proving the
 * packaged artifact round-trips to the same scene, and that a HIDDEN finite ticker under a TIMED hold
 * raises NO export preflight diagnostic. (The runtime + checklist-predicate guards on the same scene
 * live in packages/template-runtime/tests/hidden-content-fixture.test.ts.)
 */

// cwd = the package dir (apps/designer) under both turbo and `--filter exec`; the repo-root fixtures
// are two levels up.
const fixtureDir = resolve(process.cwd(), '../../fixtures/b034');

function makeExporter(): ExporterSingleFile {
  return new ExporterSingleFile({
    cgJsIife: 'var CG = { createRuntime: function () { return { ready: Promise.resolve() }; } };',
    cgCss: 'html,body{background:transparent}',
    fontsCss: '',
    assets: { bytes: async () => null } as unknown as AssetStore,
    fetchUrl: async () => new Uint8Array([1, 2, 3, 4]).buffer,
  });
}

/** Clone the scene and un-hide the timed comp's finite ticker (simulate showing it in the editor). */
function showTimedFinite(scene: Scene): Scene {
  const next = structuredClone(scene) as Scene;
  const comp = next.compositions?.find((c) => c.id === 'timedFinite');
  const ticker = comp?.layers[0]?.children[0];
  if (ticker === undefined) throw new Error('fixture drift: timedFinite ticker not found');
  (ticker as { visible: boolean }).visible = true;
  return next;
}

describe('B-034 — exporter guard against the REAL hidden-content .vcg', () => {
  it('the committed .vcg round-trips to the committed scene.json (schema-validated artifact)', async () => {
    const vcgBytes = readFileSync(resolve(fixtureDir, 'hidden-content-inert.vcg'));
    const { scene } = await unpack(new Uint8Array(vcgBytes));
    const sceneJson = JSON.parse(
      readFileSync(resolve(fixtureDir, 'hidden-content-inert.scene.json'), 'utf8'),
    ) as Scene;
    expect(scene).toEqual(sceneJson);
    // Sanity: the artifact really carries the hidden finite ticker under a TIMED hold.
    const timed = scene.compositions?.find((c) => c.id === 'timedFinite');
    const ticker = timed?.layers[0]?.children[0] as {
      type: string;
      visible: boolean;
      repeat: number;
    };
    expect(timed?.playout?.holdSource).not.toBe('content-driven'); // TIMED (auto-out + holdMs)
    expect(ticker.type).toBe('ticker');
    expect(ticker.visible).toBe(false);
    expect(ticker.repeat).toBe(2); // finite
  });

  it('a HIDDEN finite ticker under a TIMED hold raises no preflight; un-hiding it does', async () => {
    const vcgBytes = readFileSync(resolve(fixtureDir, 'hidden-content-inert.vcg'));
    const { scene } = await unpack(new Uint8Array(vcgBytes));

    // Hidden ⇒ inert ⇒ no diagnostic.
    const { issues } = await makeExporter().produce(scene);
    expect(issues.some((i) => i.code === 'ticker-finite-with-timed-hold')).toBe(false);

    // Positive control: un-hiding the SAME ticker surfaces the diagnostic for it — so the silence
    // above is the visible gate at work, not a dead path.
    const { issues: shownIssues } = await makeExporter().produce(showTimedFinite(scene));
    const info = shownIssues.find((i) => i.code === 'ticker-finite-with-timed-hold');
    expect(info).toBeDefined();
    expect(info?.elementId).toBe('hiddenFinite');
  });
});
