import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { hasEffectiveHoldDrivers, SceneSchema, type Scene } from '@cg/shared-schema';
import { createRuntime } from '../src/runtime.js';

/**
 * B-034 — the SAME guards, asserted against a REAL committed template (a schema-validated `.vcg`
 * scene with HIDDEN content), not inline constructed comps. The fixture
 * (fixtures/b034/hidden-content-inert.{scene.json,vcg}) is generated by its sibling `.gen.mjs`
 * and contains: a content-driven parent that instances a child whose ONLY content is a HIDDEN
 * infinite ticker, with a per-instance `holdOverrides` FORCE-INCLUDE on it. (The exporter guard +
 * `.vcg` round-trip live in apps/designer/tests/hidden-content-vcg-fixture.test.ts — that package
 * owns the exporter; this one owns the runtime.)
 */

function loadFixtureScene(): Scene {
  // vitest runs with cwd = the package dir (both `--filter exec` and turbo), so the repo-root fixture
  // is two levels up. (jsdom's non-`file:` `import.meta.url` rules out a URL-relative read here.)
  const p = resolve(process.cwd(), '../../fixtures/b034/hidden-content-inert.scene.json');
  return SceneSchema.parse(JSON.parse(readFileSync(p, 'utf8')));
}

function makeClock() {
  let ms = 0;
  const rafs = new Map<number, (ts: number) => void>();
  const timers: { id: number; due: number; cb: () => void }[] = [];
  let nextId = 1;
  return {
    now: () => ms,
    raf: (cb: (ts: number) => void) => {
      const id = nextId++;
      rafs.set(id, cb);
      return id;
    },
    cancel: (h: number) => {
      rafs.delete(h);
    },
    setTimeout: (cb: () => void, delay: number) => {
      const id = nextId++;
      timers.push({ id, due: ms + delay, cb });
      return id;
    },
    clearTimeout: (h: unknown) => {
      const i = timers.findIndex((t) => t.id === h);
      if (i >= 0) timers.splice(i, 1);
    },
    advance: (delta: number) => {
      ms += delta;
      const due = timers.filter((t) => t.due <= ms).sort((a, b) => a.due - b.due);
      for (const t of due) {
        const i = timers.indexOf(t);
        if (i >= 0) timers.splice(i, 1);
        t.cb();
      }
      const round = [...rafs.entries()];
      for (const [id] of round) rafs.delete(id);
      for (const [, cb] of round) cb(ms);
    },
  };
}

async function run(
  clock: ReturnType<typeof makeClock>,
  totalMs: number,
  step = 100,
): Promise<void> {
  let left = totalMs;
  while (left > 0) {
    const d = Math.min(step, left);
    clock.advance(d);
    left -= d;
    for (let i = 0; i < 6; i += 1) await Promise.resolve();
  }
}

const tickerMeasure = (node: HTMLElement): number => (node.textContent?.length ?? 0) * 10;
const onAir = (): boolean => !document.body.classList.contains('cg-pending');

/** Flip the hidden child crawl visible (simulate un-hiding it in the editor). */
function unhideChildCrawl(scene: Scene): Scene {
  const next = structuredClone(scene) as Scene;
  const child = next.compositions?.find((c) => c.id === 'childHiddenOnly');
  const crawl = child?.layers[0]?.children[0];
  if (crawl === undefined) throw new Error('fixture drift: childHiddenOnly crawl not found');
  (crawl as { visible: boolean }).visible = true;
  return next;
}

beforeEach(() => {
  document.body.innerHTML = '';
  document.body.className = '';
});
afterEach(() => {
  document.body.innerHTML = '';
  document.body.className = '';
});

describe('B-034 — guards against the REAL hidden-content fixture (.vcg scene)', () => {
  it('the fixture really contains the hidden force-included nested crawl (guards the test itself)', () => {
    const scene = loadFixtureScene();
    const inst = scene.layers[0]?.children[0] as { holdOverrides?: Record<string, boolean> };
    expect(inst.holdOverrides).toEqual({ hiddenCrawl: true }); // force-include attempt
    const child = scene.compositions?.find((c) => c.id === 'childHiddenOnly');
    const crawl = child?.layers[0]?.children[0] as {
      visible: boolean;
      repeat: string;
      type: string;
    };
    expect(crawl.type).toBe('ticker');
    expect(crawl.visible).toBe(false); // hidden
    expect(crawl.repeat).toBe('infinite');
  });

  it('the content-driven parent has NO effective drivers (the force-included hidden crawl is inert)', () => {
    const scene = loadFixtureScene();
    // Even with holdOverrides { hiddenCrawl: true }, the hidden crawl is not an effective driver ⇒
    // the comp resolves content-driven → timed (B-032). Un-hiding it restores driver participation.
    expect(hasEffectiveHoldDrivers(scene, scene.compositions)).toBe(false);
    const unhidden = unhideChildCrawl(scene);
    expect(hasEffectiveHoldDrivers(unhidden, unhidden.compositions)).toBe(true);
  });

  it('a hidden infinite crawl force-included via holdOverrides does NOT freeze the graphic (settles via timed)', async () => {
    const clock = makeClock();
    const r = createRuntime(loadFixtureScene(), { skipFontLoad: true, clock, tickerMeasure });
    await r.play({});

    await run(clock, 2000);
    expect(onAir()).toBe(true); // holding the timed 3s — NOT frozen by the force-included hidden crawl

    await run(clock, 2000); // ~4s: the timed hold elapses → settle
    expect(onAir()).toBe(false);
    r.remove();
  });
});

function loadAncestorScene(): Scene {
  const p = resolve(process.cwd(), '../../fixtures/b034/hidden-ancestor-inert.scene.json');
  return SceneSchema.parse(JSON.parse(readFileSync(p, 'utf8')));
}

describe('B-034 (ancestor) — guards against the REAL hidden-ANCESTOR fixture (the master.vcg shape)', () => {
  it('the fixture really hides an INSTANCE over a VISIBLE infinite sequence (guards the test itself)', () => {
    const scene = loadAncestorScene();
    const kids = scene.layers[0]?.children as {
      id: string;
      visible: boolean;
      holdOverrides?: Record<string, boolean>;
    }[];
    const [a, b, c] = kids;
    expect(a?.visible).toBe(false); // (a) the INSTANCE is hidden
    expect(a?.holdOverrides).toBeUndefined(); // inert PURELY because the instance is hidden (no override)
    expect(b?.visible).toBe(true); // (b) visible finite-ticker instance — drives the close
    expect(c?.holdOverrides).toEqual({ excludableSeq: false }); // (c) excluded via per-instance override
    // (a)'s child is a VISIBLE, infinite sequence — it would never complete if it counted.
    const seq = scene.compositions?.find((x) => x.id === 'compVisibleSeq')?.layers[0]
      ?.children[0] as {
      type: string;
      visible: boolean;
      repeat: string;
    };
    expect(seq.type).toBe('sequence');
    expect(seq.visible).toBe(true);
    expect(seq.repeat).toBe('infinite');
  });

  it('only the VISIBLE finite ticker is an effective driver — the hidden instance + the excluded one are inert', () => {
    const scene = loadAncestorScene();
    expect(hasEffectiveHoldDrivers(scene, scene.compositions)).toBe(true); // (b) drives
    // Remove (b) → NO effective drivers: (a) is inside a HIDDEN instance and (c) is override-excluded,
    // so both contribute nothing (resolves to timed). This isolates that (a) + (c) are truly inert.
    const withoutFinite = structuredClone(scene) as Scene;
    const root = withoutFinite.layers[0] as { children: { id: string }[] };
    root.children = root.children.filter((el) => el.id !== 'inst-finite');
    expect(hasEffectiveHoldDrivers(withoutFinite, withoutFinite.compositions)).toBe(false);
  });

  it('the parent CLOSES when the finite ticker completes — the hidden instance’s infinite sequence does NOT keep it open', async () => {
    const clock = makeClock();
    const r = createRuntime(loadAncestorScene(), { skipFontLoad: true, clock, tickerMeasure });
    await r.play({});

    await run(clock, 500);
    expect(onAir()).toBe(true); // still holding for the finite ticker's one pass

    await run(clock, 8000); // generous: the finite ticker completes → parent outros → settles
    expect(onAir()).toBe(false); // WITHOUT the subtree-skip (a)'s VISIBLE infinite sequence holds forever
    r.remove();
  });
});
